initialize:
    rotateStepDegrees: 30
    visibilityDistance: 1.0
    gridSize: 0.25
    agentType: stochastic
    continuousMode: True
    snapToGrid: False
    agentMode: locobot
    fieldOfView: 63.453048374758716 # Vertical FOV, corresponds to a horizontal FOV of 79

thor_build_id: 7676ca15870d6c9795be1ff1e7c12f65dd52474f
width: 640
height: 480
max_steps: 500
